export const currentLocales = ["en", "es"] as const;
export type CurrentLocale = (typeof currentLocales)[number];
export type CurrentPage = "home" | "solutions" | "work" | "axom" | "partners" | "about" | "discuss";

export function isCurrentLocale(value: string): value is CurrentLocale {
  return currentLocales.includes(value as CurrentLocale);
}

const sharedEvidence = {
  en: [
    { type: "SYSTEM PROFILE", maturity: "ACTIVE", title: "AXOM Factory", body: "A governed AI-native product-manufacturing system under development and real-project validation.", visual: "axom" },
    { type: "PROJECT STORY", maturity: "ACTIVE", title: "Taller Express", body: "A real service-operations product: intake, workflow, protected Human authority and contextual capability.", visual: "taller" },
    { type: "LAB DEMO", maturity: "EXPERIMENTAL", title: "Reveal Studio", body: "AI-enabled consumer experience exploring image-driven and bilingual interaction.", visual: "reveal" },
    { type: "LAB DEMO", maturity: "EXPERIMENTAL", title: "Diaspora Heat Map", body: "Geospatial and information-visualization exploration for product thinking.", visual: "diaspora" },
  ],
  es: [
    { type: "PERFIL DE SISTEMA", maturity: "ACTIVO", title: "AXOM Factory", body: "Un sistema gobernado y nativo de IA para fabricar productos digitales, en desarrollo y validación con proyectos reales.", visual: "axom" },
    { type: "HISTORIA DE PROYECTO", maturity: "ACTIVO", title: "Taller Express", body: "Un producto real de operaciones de servicio: intake, workflow, autoridad humana protegida y capacidad contextual.", visual: "taller" },
    { type: "DEMO DE LAB", maturity: "EXPERIMENTAL", title: "Reveal Studio", body: "Experiencia de consumo con IA que explora interacción visual y bilingüe.", visual: "reveal" },
    { type: "DEMO DE LAB", maturity: "EXPERIMENTAL", title: "Diaspora Heat Map", body: "Exploración geoespacial y de visualización de información para pensamiento de producto.", visual: "diaspora" },
  ],
} as const;

export const currentContent = {
  en: {
    nav: { solutions: "Solutions", work: "Work", axom: "AXOM", partners: "Partners", about: "About", discuss: "Discuss a Challenge" },
    footer: {
      prompt: "Have a product, system or AI challenge worth solving?",
      descriptor: "Product · Systems · AI",
    },
    home: {
      kicker: "PRODUCT / SYSTEMS / AI",
      title: ["Build the product.", "Improve the system.", "Put AI to useful work."],
      body: "Digital products and AI-enabled business systems, built with judgment — from product strategy and design through software and governed implementation.",
      thesisKicker: "WHAT DENYSOFT BRINGS",
      thesis: "Founder accountability, product judgment, design, software and AI-native systems — combined in one disciplined delivery practice.",
      thesisNote: "No agency theater. No invented scale. Evidence first.",
      evidenceKicker: "SELECTED EVIDENCE",
      evidenceTitle: "Work that shows how we think.",
      evidenceBody: "System profiles, active product stories, lab demos and delivered snapshots are labeled for what they are — not inflated into invented case studies.",
      projectStory: {
        label: "TALLER EXPRESS / PRODUCT + OPERATIONS",
        title: "A service system, not just a screen.",
        body: "Taller Express demonstrates how Denysoft approaches operational complexity: customer intake, service coordination, protected Human authority and contextual assistance are treated as one product system.",
        path: "Intake → Service request → Operator decision → Workflow → QA / security evidence",
      },
      axom: {
        kicker: "AXOM / SYSTEM LAYER",
        title: "Open the machine room.",
        body: "AXOM belongs to the Denysoft ecosystem, but speaks in a deeper technical register: artifacts, capabilities, governance, evaluation and bounded execution.",
        notes: [
          ["DYNAMIC EXPERTISE", "Capabilities assembled to the work."],
          ["EVIDENCE OVER INVENTION", "State and maturity remain explicit."],
          ["REPLACEABLE PROVIDERS", "Tools and models are infrastructure, not identity."],
          ["HUMAN AUTHORITY", "Consequential decisions remain governed."],
        ],
      },
      partners: {
        kicker: "PARTNERS / QUIET CAPABILITY",
        title: "Additional capability without additional theater.",
        cards: [
          ["PRODUCT SUPPORT", "Strategy, UX and product definition where a delivery team needs depth."],
          ["TECHNICAL DELIVERY", "Frontend, systems and implementation support with clear handoffs."],
          ["AI-NATIVE CAPABILITY", "Bounded AI features, agentic workflows and governed experimentation."],
        ],
      },
      founder: {
        kicker: "FOUNDER-LED ACCOUNTABILITY",
        title: "A company with a person accountable for the judgment behind the work.",
        body: "Denys Lopez leads Denysoft as a founder-led product and technology practice. The company voice stays larger than a personal brand, while accountability remains visible.",
        location: "Canada · El Salvador · International collaboration",
      },
    },
    solutions: {
      kicker: "SOLUTIONS",
      title: "Build the right thing. Then build it right.",
      body: "Product judgment, design, software and AI-native capability brought together around the challenge — not around a predetermined deliverable.",
      lensKicker: "DECISION LENS",
      lensTitle: "Technology is not the first decision.",
      lensIntro: "Start with the signal, inspect the system, then decide whether intelligence belongs in the solution.",
      lens: [
        ["SIGNAL", "What is actually changing?", "Clarify the business and user evidence before prescribing output."],
        ["SYSTEM", "Where is the constraint?", "Model the workflow, dependencies and authority boundaries."],
        ["INTELLIGENCE", "Does AI improve the system?", "Use AI only where bounded intelligence creates useful leverage."],
      ],
      pathwaysTitle: "Three ways into the work.",
      pathways: [
        ["Product", "New digital products, service experiences and customer-facing software."],
        ["Systems", "Operational workflows, internal tools, integrations and modernization."],
        ["AI-enabled capability", "Useful, bounded AI inside products and operations."],
      ],
      modelKicker: "FROM CHALLENGE TO EVIDENCE",
      modelTitle: "Strategy → specification → architecture → implementation",
      modelBody: "The process scales to the problem. Complexity is justified by evidence, not ceremony.",
    },
    work: {
      kicker: "WORK",
      title: "Evidence, not theater.",
      body: "See active systems, product stories, experiments and delivered work — labeled for what they actually are.",
      evidenceKicker: "SELECTED EVIDENCE",
      evidenceTitle: "Work that shows how we think.",
      evidenceBody: "Evidence type and maturity are separate on purpose. Active does not mean launched. Experimental does not mean production.",
    },
    axom: {
      kicker: "AXOM",
      title: "The operating system behind disciplined AI-native delivery.",
      body: "A governed path from intent to evidence — designed to preserve Human authority while using models, tools and expert capabilities as replaceable infrastructure.",
      systemKicker: "AXOM / SYSTEM LAYER",
      systemTitle: "Open the machine room.",
      systemBody: "Artifacts, capabilities, governance, evaluation and bounded execution form the system layer beneath Denysoft delivery.",
      principlesTitle: "What the system is designed to preserve.",
      principles: [
        ["Human authority", "Consequential decisions remain governed. Agents can advise and execute only inside approved boundaries."],
        ["Evidence over invention", "Maturity, state, provenance and unknowns remain explicit."],
        ["Replaceable infrastructure", "Models, providers and tools are selected for fit and can change without becoming the product identity."],
      ],
    },
    partners: {
      kicker: "PARTNERS",
      title: "Capability that integrates quietly into your delivery.",
      body: "Product, technical and AI-native support for agencies and consultancies that need additional depth without additional theater.",
      capabilityKicker: "PARTNERS / QUIET CAPABILITY",
      capabilityTitle: "Additional capability without additional theater.",
      capabilities: [
        ["PRODUCT SUPPORT", "Strategy, UX and product definition where a delivery team needs depth."],
        ["TECHNICAL DELIVERY", "Frontend, systems and implementation support with clear handoffs."],
        ["AI-NATIVE CAPABILITY", "Bounded AI features, agentic workflows and governed experimentation."],
      ],
      engagementKicker: "ENGAGEMENT MODEL",
      engagementTitle: "Clear entry points. Clear boundaries. Clean handoffs.",
      integration: [
        ["CLIENT RELATIONSHIP", "The partner remains accountable for the relationship."],
        ["PARTNER CORE", "Existing strategy and delivery remain intact."],
        ["DENYSOFT CAPABILITY", "Denysoft fills a defined capability gap."],
        ["PORTABLE HANDOFF", "Artifacts and decisions return cleanly to the partner."],
      ],
      steps: [
        ["01 / Define the gap", "Align on capability, deliverable, evidence and boundary."],
        ["02 / Integrate", "Work inside the agreed delivery model with explicit ownership."],
        ["03 / Hand off", "Artifacts, decisions and implementation context remain portable."],
      ],
    },
    about: {
      kicker: "ABOUT / FOUNDER",
      title: "Founder-led accountability. Company-level ambition.",
      body: "A product and technology practice led by Denys Lopez — with visible responsibility for the judgment behind the work.",
      founderKicker: "FOUNDER-LED ACCOUNTABILITY",
      founderTitle: "A company with a person accountable for the judgment behind the work.",
      founderBody: "Denys Lopez leads Denysoft as a founder-led product and technology practice. The company voice stays larger than a personal brand, while accountability remains visible.",
      accountabilityKicker: "ACCOUNTABILITY TRACE",
      accountabilityTitle: "The work should be able to answer who decided what — and why.",
      trace: [
        ["01 / INTENT", "What are we actually trying to change?"],
        ["02 / DECISION", "What choice was made and what evidence supported it?"],
        ["03 / BOUNDARY", "Where does automation stop and Human authority begin?"],
        ["04 / EVIDENCE", "What proves the result or tells us what to change next?"],
      ],
      principlesTitle: "How the work is meant to feel.",
      principles: [
        ["Judgment before output", "The right decision matters more than maximum production."],
        ["Clarity before theater", "Evidence, usefulness and craft over agency performance."],
        ["International by collaboration", "Canada, El Salvador and international collaboration — without invented office theater."],
      ],
    },
    discuss: {
      kicker: "DISCUSS A CHALLENGE",
      title: "Bring the challenge. We’ll define what should happen next.",
      body: "You do not need a finished brief before the conversation. The first job is to frame the problem clearly enough to decide the right next move.",
      lensKicker: "FRAMING LENS",
      lensTitle: "Turn an ambiguous problem into a decision surface.",
      prompts: [
        ["SIGNAL", "What tells you something needs to change?"],
        ["CONSTRAINT", "What is preventing progress now?"],
        ["STAKE", "What becomes valuable if this improves?"],
        ["UNKNOWN", "What do we still need to learn before deciding?"],
      ],
      intakeTitle: "A useful starting point.",
      fields: { name: "NAME", email: "EMAIL", context: "COMPANY / CONTEXT", challenge: "WHAT ARE YOU TRYING TO SOLVE?", value: "WHAT WOULD MAKE THIS VALUABLE?" },
      previewNote: "Preview intake only — submission wiring remains separately gated.",
      nextKicker: "WHAT HAPPENS NEXT",
      nextTitle: "Clarify → frame → decide the right next step.",
      nextBody: "A conversation may lead to a scoped engagement, a recommendation, or a decision not to build yet. The useful outcome is clarity, not forced conversion.",
    },
    evidence: sharedEvidence.en,
  },
  es: {
    nav: { solutions: "Soluciones", work: "Trabajo", axom: "AXOM", partners: "Partners", about: "Perfil", discuss: "Hablar de un reto" },
    footer: {
      prompt: "¿Tienes un producto, sistema o reto de IA que valga la pena resolver?",
      descriptor: "Producto · Sistemas · IA",
    },
    home: {
      kicker: "PRODUCTO / SISTEMAS / IA",
      title: ["Construye el producto.", "Mejora el sistema.", "Pon la IA a trabajar con propósito."],
      body: "Productos digitales y sistemas de negocio con IA, construidos con criterio — desde estrategia y diseño de producto hasta software e implementación gobernada.",
      thesisKicker: "LO QUE APORTA DENYSOFT",
      thesis: "Responsabilidad del founder, criterio de producto, diseño, software y sistemas nativos de IA — combinados en una práctica disciplinada de entrega.",
      thesisNote: "Sin teatro de agencia. Sin escala inventada. Evidencia primero.",
      evidenceKicker: "EVIDENCIA SELECCIONADA",
      evidenceTitle: "Trabajo que muestra cómo pensamos.",
      evidenceBody: "Perfiles de sistema, historias de producto activas, demos de laboratorio y snapshots entregados se etiquetan por lo que son — sin inflarlos en case studies inventados.",
      projectStory: {
        label: "TALLER EXPRESS / PRODUCTO + OPERACIONES",
        title: "Un sistema de servicio, no solo una pantalla.",
        body: "Taller Express demuestra cómo Denysoft aborda complejidad operativa: intake de cliente, coordinación de servicio, autoridad humana protegida y asistencia contextual se tratan como un solo sistema de producto.",
        path: "Intake → Solicitud → Decisión del operador → Workflow → Evidencia QA / seguridad",
      },
      axom: {
        kicker: "AXOM / CAPA DE SISTEMA",
        title: "Abre la sala de máquinas.",
        body: "AXOM pertenece al ecosistema Denysoft, pero habla en un registro técnico más profundo: artefactos, capacidades, gobernanza, evaluación y ejecución acotada.",
        notes: [
          ["EXPERTISE DINÁMICO", "Capacidades ensambladas para el trabajo."],
          ["EVIDENCIA SOBRE INVENCIÓN", "Estado y madurez permanecen explícitos."],
          ["PROVEEDORES REEMPLAZABLES", "Herramientas y modelos son infraestructura, no identidad."],
          ["AUTORIDAD HUMANA", "Las decisiones con consecuencias permanecen gobernadas."],
        ],
      },
      partners: {
        kicker: "PARTNERS / CAPACIDAD DISCRETA",
        title: "Capacidad adicional sin teatro adicional.",
        cards: [
          ["SOPORTE DE PRODUCTO", "Estrategia, UX y definición de producto donde un equipo necesita profundidad."],
          ["ENTREGA TÉCNICA", "Frontend, sistemas e implementación con handoffs claros."],
          ["CAPACIDAD NATIVA DE IA", "Funciones de IA acotadas, workflows agénticos y experimentación gobernada."],
        ],
      },
      founder: {
        kicker: "RESPONSABILIDAD FOUNDER-LED",
        title: "Una empresa con una persona responsable del criterio detrás del trabajo.",
        body: "Denys Lopez lidera Denysoft como práctica founder-led de producto y tecnología. La voz de la compañía permanece más grande que una marca personal, mientras la responsabilidad sigue visible.",
        location: "Canadá · El Salvador · Colaboración internacional",
      },
    },
    solutions: {
      kicker: "SOLUCIONES",
      title: "Construye lo correcto. Luego constrúyelo bien.",
      body: "Criterio de producto, diseño, software y capacidad nativa de IA reunidos alrededor del reto — no alrededor de un entregable predeterminado.",
      lensKicker: "LENTE DE DECISIÓN",
      lensTitle: "La tecnología no es la primera decisión.",
      lensIntro: "Comienza con la señal, inspecciona el sistema y luego decide si la inteligencia debe formar parte de la solución.",
      lens: [
        ["SEÑAL", "¿Qué está cambiando realmente?", "Aclara la evidencia de negocio y usuario antes de prescribir output."],
        ["SISTEMA", "¿Dónde está la restricción?", "Modela workflow, dependencias y límites de autoridad."],
        ["INTELIGENCIA", "¿La IA mejora el sistema?", "Usa IA solo donde inteligencia acotada cree apalancamiento útil."],
      ],
      pathwaysTitle: "Tres formas de entrar al trabajo.",
      pathways: [
        ["Producto", "Nuevos productos digitales, experiencias de servicio y software orientado al cliente."],
        ["Sistemas", "Workflows operativos, herramientas internas, integraciones y modernización."],
        ["Capacidad con IA", "IA útil y acotada dentro de productos y operaciones."],
      ],
      modelKicker: "DEL RETO A LA EVIDENCIA",
      modelTitle: "Estrategia → especificación → arquitectura → implementación",
      modelBody: "El proceso escala al problema. La complejidad se justifica con evidencia, no con ceremonia.",
    },
    work: {
      kicker: "TRABAJO",
      title: "Evidencia, no teatro.",
      body: "Sistemas activos, historias de producto, experimentos y trabajo entregado — etiquetados por lo que realmente son.",
      evidenceKicker: "EVIDENCIA SELECCIONADA",
      evidenceTitle: "Trabajo que muestra cómo pensamos.",
      evidenceBody: "El tipo de evidencia y la madurez están separados a propósito. Activo no significa lanzado. Experimental no significa producción.",
    },
    axom: {
      kicker: "AXOM",
      title: "El sistema operativo detrás de una entrega nativa de IA disciplinada.",
      body: "Un camino gobernado desde intención hasta evidencia — diseñado para preservar autoridad humana usando modelos, herramientas y capacidades expertas como infraestructura reemplazable.",
      systemKicker: "AXOM / CAPA DE SISTEMA",
      systemTitle: "Abre la sala de máquinas.",
      systemBody: "Artefactos, capacidades, gobernanza, evaluación y ejecución acotada forman la capa de sistema debajo de la entrega de Denysoft.",
      principlesTitle: "Lo que el sistema está diseñado para preservar.",
      principles: [
        ["Autoridad humana", "Las decisiones con consecuencias permanecen gobernadas. Los agentes asesoran y ejecutan solo dentro de límites aprobados."],
        ["Evidencia sobre invención", "Madurez, estado, procedencia y desconocidos permanecen explícitos."],
        ["Infraestructura reemplazable", "Modelos, proveedores y herramientas se seleccionan por ajuste y pueden cambiar sin convertirse en identidad del producto."],
      ],
    },
    partners: {
      kicker: "PARTNERS",
      title: "Capacidad que se integra discretamente en tu entrega.",
      body: "Soporte de producto, técnico y nativo de IA para agencias y consultoras que necesitan mayor profundidad sin mayor teatro.",
      capabilityKicker: "PARTNERS / CAPACIDAD DISCRETA",
      capabilityTitle: "Capacidad adicional sin teatro adicional.",
      capabilities: [
        ["SOPORTE DE PRODUCTO", "Estrategia, UX y definición de producto donde un equipo necesita profundidad."],
        ["ENTREGA TÉCNICA", "Frontend, sistemas e implementación con handoffs claros."],
        ["CAPACIDAD NATIVA DE IA", "Funciones de IA acotadas, workflows agénticos y experimentación gobernada."],
      ],
      engagementKicker: "MODELO DE COLABORACIÓN",
      engagementTitle: "Entradas claras. Límites claros. Handoffs limpios.",
      integration: [
        ["RELACIÓN CON CLIENTE", "El partner conserva responsabilidad sobre la relación."],
        ["NÚCLEO DEL PARTNER", "La estrategia y entrega existentes permanecen intactas."],
        ["CAPACIDAD DENYSOFT", "Denysoft cubre una brecha de capacidad definida."],
        ["HANDOFF PORTABLE", "Artefactos y decisiones regresan limpiamente al partner."],
      ],
      steps: [
        ["01 / Define la brecha", "Alinea capacidad, entregable, evidencia y límite."],
        ["02 / Integra", "Trabaja dentro del modelo acordado con ownership explícito."],
        ["03 / Entrega", "Artefactos, decisiones y contexto de implementación permanecen portables."],
      ],
    },
    about: {
      kicker: "PERFIL / FOUNDER",
      title: "Responsabilidad founder-led. Ambición a nivel de compañía.",
      body: "Una práctica de producto y tecnología liderada por Denys Lopez — con responsabilidad visible por el criterio detrás del trabajo.",
      founderKicker: "RESPONSABILIDAD FOUNDER-LED",
      founderTitle: "Una empresa con una persona responsable del criterio detrás del trabajo.",
      founderBody: "Denys Lopez lidera Denysoft como práctica founder-led de producto y tecnología. La voz de la compañía permanece más grande que una marca personal, mientras la responsabilidad sigue visible.",
      accountabilityKicker: "TRAZA DE RESPONSABILIDAD",
      accountabilityTitle: "El trabajo debe poder responder quién decidió qué — y por qué.",
      trace: [
        ["01 / INTENCIÓN", "¿Qué estamos tratando de cambiar realmente?"],
        ["02 / DECISIÓN", "¿Qué elección se hizo y qué evidencia la soportó?"],
        ["03 / LÍMITE", "¿Dónde termina la automatización y comienza la autoridad humana?"],
        ["04 / EVIDENCIA", "¿Qué prueba el resultado o indica qué debemos cambiar después?"],
      ],
      principlesTitle: "Cómo debe sentirse el trabajo.",
      principles: [
        ["Criterio antes que output", "La decisión correcta importa más que producción máxima."],
        ["Claridad antes que teatro", "Evidencia, utilidad y craft por encima del performance de agencia."],
        ["Internacional por colaboración", "Canadá, El Salvador y colaboración internacional — sin teatro de oficinas inventadas."],
      ],
    },
    discuss: {
      kicker: "HABLEMOS DE UN RETO",
      title: "Trae el reto. Definiremos qué debería pasar después.",
      body: "No necesitas un brief terminado antes de conversar. El primer trabajo es enmarcar el problema con suficiente claridad para decidir el siguiente movimiento correcto.",
      lensKicker: "LENTE DE ENMARCADO",
      lensTitle: "Convierte un problema ambiguo en una superficie de decisión.",
      prompts: [
        ["SEÑAL", "¿Qué indica que algo necesita cambiar?"],
        ["RESTRICCIÓN", "¿Qué está impidiendo el progreso ahora?"],
        ["VALOR", "¿Qué se vuelve valioso si esto mejora?"],
        ["DESCONOCIDO", "¿Qué debemos aprender antes de decidir?"],
      ],
      intakeTitle: "Un punto de partida útil.",
      fields: { name: "NOMBRE", email: "EMAIL", context: "EMPRESA / CONTEXTO", challenge: "¿QUÉ ESTÁS TRATANDO DE RESOLVER?", value: "¿QUÉ HARÍA ESTO VALIOSO?" },
      previewNote: "Intake de Preview únicamente — la conexión de envío permanece separadamente gobernada.",
      nextKicker: "QUÉ PASA DESPUÉS",
      nextTitle: "Aclarar → enmarcar → decidir el siguiente paso correcto.",
      nextBody: "Una conversación puede llevar a un engagement acotado, una recomendación o una decisión de no construir todavía. El resultado útil es claridad, no conversión forzada.",
    },
    evidence: sharedEvidence.es,
  },
} as const;

export function getCurrentContent(locale: CurrentLocale) {
  return currentContent[locale];
}
